name: Build and Deploy Static
on:
  # Run on push to master bc we like to live dangerously
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup AWS Creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    # - name: Build It
    #   run: yarn install && npm run-script build
    # - name: Deploy It
    #   run: aws s3 sync ./dist/ s3://<your-website-bucket> --delete
